#cloud-config

write_files:
  - path: /root/swarm-helper.py
    permissions: 0755
    content: |
      #!/usr/bin/env python
      from bottle import get, run, abort
      from subprocess import check_output
      from socket import gethostname
      from signal import signal, setitimer, ITIMER_REAL, SIGALRM

      def cleanup(signum, frame):
          try:
              nodes = check_output('docker node ls', shell=True).strip()
              down = map(lambda x: x.split()[1], filter(lambda x: 'Down' in x, nodes.split("\n")))
              for node in down:
                  check_output('docker node rm ' + node, shell=True)
          except:
              pass

      @get("/join/worker")
      def token():
          return check_output('docker swarm join-token -q worker', shell=True).strip()

      @get("/join/master")
      def token():
          return check_output('docker swarm join-token -q master', shell=True).strip()

      @get("/drain/<hostname>")
      def drain(hostname):
          try:
              return check_output('docker node update --availability drain ' + hostname, shell=True).strip()
          except:
              abort(404, "node not found")

      if gethostname() == 'master0':
          try:
              check_output('docker swarm init', shell=True)
          except:
              pass
          signal(SIGALRM, cleanup)
          setitimer(ITIMER_REAL, 10, 10)
          run(port=1337,host='0.0.0.0')
  - path: /etc/systemd/system/swarm-helper.service
    permissions: 0444
    content: |
      [Unit]
      Description=Swarm Helper
      DefaultDependencies=no
      After=multi-user.target
      [Service]
      Type=oneshot
      ExecStart=/root/swarm-helper.py
      [Install]
      WantedBy=multi-user.target
  - path: /etc/waagent.conf
    permissions: 0444
    content: |
      ResourceDisk.Format=y
      ResourceDisk.Filesystem=ext4
      ResourceDisk.MountPoint=/mnt/resource
      ResourceDisk.EnableSwap=y
      ResourceDisk.SwapSizeMB=2048

mounts:
  - - //${STORAGE_ACCOUNT_NAME}.file.core.windows.net/${SHARE_NAME}
    - /srv
    - cifs
    - vers=3.0,username=${STORAGE_ACCOUNT_NAME},password=${STORAGE_ACCOUNT_KEY},dir_mode=0700,file_mode=0600,uid=1000,gid=1000,noperm,,iocharset=utf8


packages:
  - ntp
  - tmux
  - htop
  - vim
  - fail2ban
  - python-bottle
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

# Install Docker, for production, consider pinning to stable versions
runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose
  - systemctl enable swarm-helper
  - systemctl start swarm-helper
